small fix for commit e78c36be
java.lang.AssertionError: A TraceCheckLock wants to use this ManagedScript without locking
  at de.uni_freiburg.informatik.ultimate.lib.smtlibutils.ManagedScript.echo(ManagedScript.java:175)
  at de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.singletracecheck.TraceCheck.computeRcfgProgramExecutionAndDecodeBranches(TraceCheck.java:354)